# Generated by Django 3.1.1 on 2020-10-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('theta', models.FloatField()),
            ],
        ),
    ]
