# Generated by Django 3.1.1 on 2020-10-03 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('uiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloodpressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_measured', models.DateTimeField(default=django.utils.timezone.now)),
                ('systolic', models.PositiveIntegerField()),
                ('diastolic', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
    ]
